name: algo-trader
services:
  ib-gateway:
    restart: always
    image: ghcr.io/gnzsnz/ib-gateway:latest
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE}
      TWS_ACCEPT_INCOMING: ${TWS_ACCEPT_INCOMING}
      READ_ONLY_API: ${READ_ONLY_API}
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD}
      TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION}
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME}
      RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT}
      EXISTING_SESSION_DETECTED_ACTION: ${EXISTING_SESSION_DETECTED_ACTION}
      ALLOW_BLIND_TRADING: ${ALLOW_BLIND_TRADING}
      TIME_ZONE: ${TIME_ZONE}
      BYPASS_WARNING: ${BYPASS_WARNING}
    ports:
      - "127.0.0.1:4001:4003"
      - "127.0.0.1:4002:4004"
      - "127.0.0.1:5900:5900"

  ibtrader:
    image: rogerzhuang/ibtrader:latest
    restart: always
    depends_on:
      - ib-gateway
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      # Connection settings
      - IB_HOST=ib-gateway
      - IB_PORT=4003
      - IB_ACCOUNT_ID=U8518146

      # Trading settings
      - TOTAL_CAPITAL=500000

      # Pairs Trading Strategy
      - PAIRS_CAPITAL_PCT=0.2
      - PAIRS_ENABLED=true

      # Option Write Strategy 1
      - OPTION_WRITE_1_CAPITAL_PCT=0.4
      - OPTION_WRITE_1_ENABLED=true

      # Option Write Strategy 2
      - OPTION_WRITE_2_CAPITAL_PCT=0.4
      - OPTION_WRITE_2_ENABLED=true
